# Generated by Django 5.0.3 on 2026-01-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sismo',
            name='detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
